name: Release

on:
  push:
    tags:
    - 'v*' # We only push on the main tagging, not the language specific tags
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      packages: write

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    
    - name: Log into ghcr.io
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build services container
      run: make services-images

    - name: Tag image
      run: docker tag protoc-services ghcr.io/${{ github.repository }}:${{ github.ref_name }}

    - name: Push image
      run: docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}
